import { Col, Row, Container, Tab, Nav } from "react-bootstrap";
import { ProjectCard } from "./ProjectCard";
import colorSharp2 from "../assets/img/color-sharp2.png";
import weatherapp from "../assets/img/weatherapp.png";
import justajoke from "../assets/img/justajoke.png";
import sudokusolver from "../assets/img/sudokusolver.png";
import projectsicon from "../assets/img/projectsicon.svg";
import tic from "../assets/img/tic-tac-toe.png";
import compressor from "../assets/img/filecompressor.png";



export const Projects = () => {
    const Webprojects = [
         {
            title: "Weather App",
            description: <p>Experience the Weather App, provides up-to-date weather forecasts tailored to your location. Stay informed with accurate weather data, including temperature, and humidity chances.</p>,
            imgUrl: weatherapp,
            linkUrl: "https://github.com/shivaramkotla/weather-app",
         },
       
         {
            title: "Tic-Tac-Toe",
           
                
            description: (
                <p>
                    This is a basic Tic Tac Toe game built using HTML, CSS, 
                    and JavaScript.Players take turns placing X or O on a 3x3 grid. 
                    The game checks for a winner or draw after each move and can be restarted with a click.
                </p>
            ),
            imgUrl: tic,
            linkUrl: "https://github.com/shivaramkotla/tic-tac-toe-game",
        },
                
        {
            title: "Just A Joke",
            description: (
                <p>
                    This is a basic Google extension that generates a random joke
                    when tapped. It uses an API from the browser and fetches a
                    random joke generated by that site.
                </p>
            ),
            imgUrl: justajoke,
            
        },
    ];

    const Progprojects = [
        {
            title: "SUDOKU Solver",
            description:
                "Whether you're a Sudoku pro or just enjoy a good brain teaser, this tool will make solving a breeze. This might help you to compare your results with its actual solution. Used simple algorithms like recursion and backtracking to achieve this, which was written in Java programming language.",
            imgUrl: sudokusolver,
            
        },
         {
            title: "File Compressor",
            description:"Used Huffman coding techniques to compress the text.",
            imgUrl: compressor,
           
        },
    ];

    return (
        <section className='project' id='projects'>
            <Container>
                <Row>
                    <Col>
                        <div className="project-bx">
                            <h2 style={{ color: 'white' }}>
                                Projects
                                <div style={{ display: 'flex', justifyContent: 'space-around' }}>
                                    <img
                                        src={projectsicon}
                                        alt="Projects-img"
                                        style={{ height: '50px', width: '50px' }}
                                    />
                                </div>
                            </h2>
                            <p>
                                This section describes my projects from different fields. These
                                are the projects I've developed as an outcome of my knowledge in
                                different courses. Lots of research and many tutors helped me to
                                develop them. It encompasses a range of technical and soft skills
                                that I have developed through online courses, hands-on projects,
                                and professional experiences.
                            </p>
                            <Tab.Container id="projects-tabs" defaultActiveKey="first">
                                <Nav
                                    variant="tabs"
                                    className="nav-pills mb-5 justify-content-center align-items-center"
                                    id="pills-tab"
                                >
                                    <Nav.Item>
                                        <Nav.Link eventKey="first">Web Development</Nav.Link>
                                    </Nav.Item>
                                    <Nav.Item>
                                        <Nav.Link eventKey="second">Programming</Nav.Link>
                                    </Nav.Item>
                                </Nav>
                                <Tab.Content>
                                    <Tab.Pane eventKey="first">
                                        <Row>
                                            {Webprojects.map((project, index) => (
                                                <ProjectCard key={index} {...project} />
                                            ))}
                                        </Row>
                                    </Tab.Pane>
                                    <Tab.Pane eventKey="second">
                                        <Row>
                                            {Progprojects.map((project, index) => (
                                                <ProjectCard key={index} {...project} />
                                            ))}
                                        </Row>
                                    </Tab.Pane>
                                </Tab.Content>
                            </Tab.Container>
                        </div>
                    </Col>
                </Row>
            </Container>
            <img className='bg-img-right' src={colorSharp2} alt="Background" />
        </section>
    );
};
